# Create docker compose for the svelte app

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
      - "5173:5173"
    environment:
      - PUBLIC_GITHUB_PROFILE=${PUBLIC_GITHUB_PROFILE}
      - PUBLIC_REPOSITORY_URL=${PUBLIC_REPOSITORY_URL}
      - PUBLIC_DOCS_URL=${PUBLIC_DOCS_URL}
      - PUBLIC_GITHUB_STARS_URL=${PUBLIC_GITHUB_STARS_URL}
      - PUBLIC_BASE_URL=${PUBLIC_BASE_URL}
      - PUBLIC_OPENAI_MODEL=${PUBLIC_OPENAI_MODEL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FORTUNE_API=${FORTUNE_API}
      - PUBLIC_POCKETBASE_URL=${PUBLIC_POCKETBASE_URL}
      - PUBLIC_POCKETBASE_ADMIN=${PUBLIC_POCKETBASE_ADMIN}
      - REDIRECT_URL=${REDIRECT_URL}
      - GOOGLE_FORM_URL=${GOOGLE_FORM_URL}
      - FORM_PAYLOAD_FIRST_NAME=${FORM_PAYLOAD_FIRST_NAME}
      - FORM_PAYLOAD_LAST_NAME=${FORM_PAYLOAD_LAST_NAME}
      - FORM_PAYLOAD_TYPE=${FORM_PAYLOAD_TYPE}
      - FORM_PAYLOAD_PRIORITY=${FORM_PAYLOAD_PRIORITY}
      - FORM_PAYLOAD_MESSAGE=${FORM_PAYLOAD_MESSAGE}
      - FORM_PAYLOAD_EMAIL=${FORM_PAYLOAD_EMAIL}
      - SECRET_STRIPE_KEY=${SECRET_STRIPE_KEY}
      - PUBLIC_STRIPE_KEY=${PUBLIC_STRIPE_KEY}
      - TMDB_API_KEY=${TMDB_API_KEY}
    env_file:
      - .env